# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\win10\Desktop\newPYprj\Ui\FormOrderMob.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
import os
import sys

from PyQt5 import QtCore, QtGui
sys.path.append(os.getcwd())
import lib.JPMvc.JPWidgets as QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 518)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.butSave = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ico/save.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSave.setIcon(icon)
        self.butSave.setIconSize(QtCore.QSize(32, 32))
        self.butSave.setObjectName("butSave")
        self.horizontalLayout_3.addWidget(self.butSave)
        self.butPrint = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/ico/printer.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butPrint.setIcon(icon1)
        self.butPrint.setIconSize(QtCore.QSize(32, 32))
        self.butPrint.setObjectName("butPrint")
        self.horizontalLayout_3.addWidget(self.butPrint)
        self.butPDF = QtWidgets.QPushButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/ico/pdf.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butPDF.setIcon(icon2)
        self.butPDF.setIconSize(QtCore.QSize(32, 32))
        self.butPDF.setObjectName("butPDF")
        self.horizontalLayout_3.addWidget(self.butPDF)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fOrderID = QtWidgets.QLineEdit(Form)
        self.fOrderID.setMinimumSize(QtCore.QSize(300, 0))
        self.fOrderID.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fOrderID.setFont(font)
        self.fOrderID.setText("")
        self.fOrderID.setAlignment(QtCore.Qt.AlignCenter)
        self.fOrderID.setObjectName("fOrderID")
        self.horizontalLayout.addWidget(self.fOrderID)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(3, -1, 0, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.fEndereco = QtWidgets.QLineEdit(Form)
        self.fEndereco.setMinimumSize(QtCore.QSize(0, 25))
        self.fEndereco.setSizeIncrement(QtCore.QSize(0, 25))
        self.fEndereco.setPlaceholderText("")
        self.fEndereco.setClearButtonEnabled(True)
        self.fEndereco.setObjectName("fEndereco")
        self.gridLayout.addWidget(self.fEndereco, 2, 2, 1, 3)
        self.fSucursal = QtWidgets.QCheckBox(Form)
        self.fSucursal.setMinimumSize(QtCore.QSize(0, 25))
        self.fSucursal.setSizeIncrement(QtCore.QSize(0, 25))
        self.fSucursal.setObjectName("fSucursal")
        self.gridLayout.addWidget(self.fSucursal, 1, 6, 1, 1)
        self.fCelular = QtWidgets.QLineEdit(Form)
        self.fCelular.setMinimumSize(QtCore.QSize(0, 25))
        self.fCelular.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCelular.setClearButtonEnabled(True)
        self.fCelular.setObjectName("fCelular")
        self.gridLayout.addWidget(self.fCelular, 3, 4, 1, 1)
        self.fRequiredDeliveryDate = QtWidgets.QDateEdit(Form)
        self.fRequiredDeliveryDate.setMinimumSize(QtCore.QSize(0, 25))
        self.fRequiredDeliveryDate.setSizeIncrement(QtCore.QSize(0, 25))
        self.fRequiredDeliveryDate.setCalendarPopup(True)
        self.fRequiredDeliveryDate.setObjectName("fRequiredDeliveryDate")
        self.gridLayout.addWidget(self.fRequiredDeliveryDate, 0, 6, 1, 1)
        self.fNUIT = QtWidgets.QLineEdit(Form)
        self.fNUIT.setMinimumSize(QtCore.QSize(0, 25))
        self.fNUIT.setSizeIncrement(QtCore.QSize(0, 25))
        self.fNUIT.setObjectName("fNUIT")
        self.gridLayout.addWidget(self.fNUIT, 1, 4, 1, 2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_7.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.fContato = QtWidgets.QComboBox(Form)
        self.fContato.setMinimumSize(QtCore.QSize(0, 25))
        self.fContato.setSizeIncrement(QtCore.QSize(0, 25))
        self.fContato.setProperty("clearButtonEnabled", True)
        self.fContato.setObjectName("fContato")
        self.gridLayout.addWidget(self.fContato, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_12.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 5, 1, 1)
        self.fTelefone = QtWidgets.QLineEdit(Form)
        self.fTelefone.setMinimumSize(QtCore.QSize(0, 25))
        self.fTelefone.setSizeIncrement(QtCore.QSize(0, 25))
        self.fTelefone.setClearButtonEnabled(True)
        self.fTelefone.setObjectName("fTelefone")
        self.gridLayout.addWidget(self.fTelefone, 3, 6, 1, 1)
        self.fCity = QtWidgets.QLineEdit(Form)
        self.fCity.setMinimumSize(QtCore.QSize(0, 25))
        self.fCity.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCity.setClearButtonEnabled(True)
        self.fCity.setObjectName("fCity")
        self.gridLayout.addWidget(self.fCity, 2, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_11.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.fVendedorID = QtWidgets.QComboBox(Form)
        self.fVendedorID.setMinimumSize(QtCore.QSize(0, 25))
        self.fVendedorID.setSizeIncrement(QtCore.QSize(0, 25))
        self.fVendedorID.setProperty("clearButtonEnabled", True)
        self.fVendedorID.setObjectName("fVendedorID")
        self.gridLayout.addWidget(self.fVendedorID, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.fCustomerID = QtWidgets.QComboBox(Form)
        self.fCustomerID.setMinimumSize(QtCore.QSize(300, 25))
        self.fCustomerID.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCustomerID.setObjectName("fCustomerID")
        self.gridLayout.addWidget(self.fCustomerID, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.fOrderDate = QtWidgets.QDateEdit(Form)
        self.fOrderDate.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fOrderDate.setCalendarPopup(True)
        self.fOrderDate.setObjectName("fOrderDate")
        self.gridLayout.addWidget(self.fOrderDate, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setMinimumSize(QtCore.QSize(0, 250))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fNote = QtWidgets.QTextEdit(Form)
        self.fNote.setToolTipDuration(-1)
        self.fNote.setStatusTip("")
        self.fNote.setWhatsThis("")
        self.fNote.setAccessibleName("")
        self.fNote.setLineWidth(-1)
        self.fNote.setObjectName("fNote")
        self.verticalLayout.addWidget(self.fNote)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.temp = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.temp.sizePolicy().hasHeightForWidth())
        self.temp.setSizePolicy(sizePolicy)
        self.temp.setObjectName("temp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.temp)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.temp)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(150, 25))
        self.label.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                                | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fAmount = QtWidgets.QLineEdit(self.temp)
        self.fAmount.setMinimumSize(QtCore.QSize(0, 25))
        self.fAmount.setMaximumSize(QtCore.QSize(150, 25))
        self.fAmount.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fAmount.setFont(font)
        self.fAmount.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fAmount.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.fAmount.setReadOnly(True)
        self.fAmount.setObjectName("fAmount")
        self.gridLayout_2.addWidget(self.fAmount, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.temp)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(150, 25))
        self.label_13.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_13.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.fDesconto = QtWidgets.QLineEdit(self.temp)
        self.fDesconto.setMinimumSize(QtCore.QSize(0, 25))
        self.fDesconto.setMaximumSize(QtCore.QSize(150, 25))
        self.fDesconto.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fDesconto.setFont(font)
        self.fDesconto.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fDesconto.setAlignment(QtCore.Qt.AlignRight
                                    | QtCore.Qt.AlignTrailing
                                    | QtCore.Qt.AlignVCenter)
        self.fDesconto.setObjectName("fDesconto")
        self.gridLayout_2.addWidget(self.fDesconto, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.temp)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(150, 25))
        self.label_14.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_14.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.fTax = QtWidgets.QLineEdit(self.temp)
        self.fTax.setMinimumSize(QtCore.QSize(0, 25))
        self.fTax.setMaximumSize(QtCore.QSize(150, 25))
        self.fTax.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fTax.setFont(font)
        self.fTax.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fTax.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                               | QtCore.Qt.AlignVCenter)
        self.fTax.setObjectName("fTax")
        self.gridLayout_2.addWidget(self.fTax, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.temp)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setMaximumSize(QtCore.QSize(150, 25))
        self.label_15.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_15.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.fPayable = QtWidgets.QLineEdit(self.temp)
        self.fPayable.setMinimumSize(QtCore.QSize(0, 25))
        self.fPayable.setMaximumSize(QtCore.QSize(150, 25))
        self.fPayable.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fPayable.setFont(font)
        self.fPayable.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fPayable.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.fPayable.setReadOnly(True)
        self.fPayable.setObjectName("fPayable")
        self.gridLayout_2.addWidget(self.fPayable, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.temp)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Order"))
        self.butSave.setText(_translate("Form", "Save"))
        self.butPrint.setText(_translate("Form", "Print"))
        self.butPDF.setText(_translate("Form", "PDF"))
        self.label_2.setText(_translate("Form", "NO."))
        self.fSucursal.setText(_translate("Form", "Sucursal"))
        self.fRequiredDeliveryDate.setDisplayFormat(
            _translate("Form", "yyyy-MM-dd"))
        self.label_7.setText(_translate("Form", "税号NUIT:"))
        self.label_9.setText(_translate("Form", "地址Endereco:"))
        self.label_8.setText(_translate("Form", "城市City:"))
        self.label_12.setText(_translate("Form", "电话Tel:"))
        self.label_4.setText(_translate("Form", "交货日期Date:"))
        self.label_11.setText(_translate("Form", "联系人Contato:"))
        self.label_6.setText(_translate("Form", "客户名Cliente:"))
        self.label_10.setText(_translate("Form", "手机Celular:"))
        self.fCustomerID.setProperty(
            "placeholderText", _translate("Form", "Please select a cliente."))
        self.label_5.setText(_translate("Form", "销售Vendedor:"))
        self.label_3.setText(_translate("Form", "日期Date:"))
        self.fOrderDate.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.fNote.setPlaceholderText(_translate("Form", "Note："))
        self.label.setText(_translate("Form", "金额合计SubTota:"))
        self.label_13.setText(_translate("Form", "折扣Desconto:"))
        self.label_14.setText(_translate("Form", "税金IVA:"))
        self.label_15.setText(_translate("Form", "应付金额Valor a Pagar:"))

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 518)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.butSave = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ico/save.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSave.setIcon(icon)
        self.butSave.setIconSize(QtCore.QSize(32, 32))
        self.butSave.setObjectName("butSave")
        self.horizontalLayout_3.addWidget(self.butSave)
        self.butPrint = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/ico/printer.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butPrint.setIcon(icon1)
        self.butPrint.setIconSize(QtCore.QSize(32, 32))
        self.butPrint.setObjectName("butPrint")
        self.horizontalLayout_3.addWidget(self.butPrint)
        self.butPDF = QtWidgets.QPushButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/ico/pdf.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butPDF.setIcon(icon2)
        self.butPDF.setIconSize(QtCore.QSize(32, 32))
        self.butPDF.setObjectName("butPDF")
        self.horizontalLayout_3.addWidget(self.butPDF)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fOrderID = QtWidgets.QLineEdit(Form)
        self.fOrderID.setMinimumSize(QtCore.QSize(300, 0))
        self.fOrderID.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fOrderID.setFont(font)
        self.fOrderID.setText("")
        self.fOrderID.setAlignment(QtCore.Qt.AlignCenter)
        self.fOrderID.setObjectName("fOrderID")
        self.horizontalLayout.addWidget(self.fOrderID)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(3, -1, 0, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.fEndereco = QtWidgets.QLineEdit(Form)
        self.fEndereco.setMinimumSize(QtCore.QSize(0, 25))
        self.fEndereco.setSizeIncrement(QtCore.QSize(0, 25))
        self.fEndereco.setPlaceholderText("")
        self.fEndereco.setClearButtonEnabled(True)
        self.fEndereco.setObjectName("fEndereco")
        self.gridLayout.addWidget(self.fEndereco, 2, 2, 1, 3)
        self.fSucursal = QtWidgets.QCheckBox(Form)
        self.fSucursal.setMinimumSize(QtCore.QSize(0, 25))
        self.fSucursal.setSizeIncrement(QtCore.QSize(0, 25))
        self.fSucursal.setObjectName("fSucursal")
        self.gridLayout.addWidget(self.fSucursal, 1, 6, 1, 1)
        self.fCelular = QtWidgets.QLineEdit(Form)
        self.fCelular.setMinimumSize(QtCore.QSize(0, 25))
        self.fCelular.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCelular.setClearButtonEnabled(True)
        self.fCelular.setObjectName("fCelular")
        self.gridLayout.addWidget(self.fCelular, 3, 4, 1, 1)
        self.fRequiredDeliveryDate = QtWidgets.QDateEdit(Form)
        self.fRequiredDeliveryDate.setMinimumSize(QtCore.QSize(0, 25))
        self.fRequiredDeliveryDate.setSizeIncrement(QtCore.QSize(0, 25))
        self.fRequiredDeliveryDate.setCalendarPopup(True)
        self.fRequiredDeliveryDate.setObjectName("fRequiredDeliveryDate")
        self.gridLayout.addWidget(self.fRequiredDeliveryDate, 0, 6, 1, 1)
        self.fNUIT = QtWidgets.QLineEdit(Form)
        self.fNUIT.setMinimumSize(QtCore.QSize(0, 25))
        self.fNUIT.setSizeIncrement(QtCore.QSize(0, 25))
        self.fNUIT.setObjectName("fNUIT")
        self.gridLayout.addWidget(self.fNUIT, 1, 4, 1, 2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_7.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.fContato = QtWidgets.QComboBox(Form)
        self.fContato.setMinimumSize(QtCore.QSize(0, 25))
        self.fContato.setSizeIncrement(QtCore.QSize(0, 25))
        self.fContato.setProperty("clearButtonEnabled", True)
        self.fContato.setObjectName("fContato")
        self.gridLayout.addWidget(self.fContato, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_12.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 5, 1, 1)
        self.fTelefone = QtWidgets.QLineEdit(Form)
        self.fTelefone.setMinimumSize(QtCore.QSize(0, 25))
        self.fTelefone.setSizeIncrement(QtCore.QSize(0, 25))
        self.fTelefone.setClearButtonEnabled(True)
        self.fTelefone.setObjectName("fTelefone")
        self.gridLayout.addWidget(self.fTelefone, 3, 6, 1, 1)
        self.fCity = QtWidgets.QLineEdit(Form)
        self.fCity.setMinimumSize(QtCore.QSize(0, 25))
        self.fCity.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCity.setClearButtonEnabled(True)
        self.fCity.setObjectName("fCity")
        self.gridLayout.addWidget(self.fCity, 2, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_11.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.fVendedorID = QtWidgets.QComboBox(Form)
        self.fVendedorID.setMinimumSize(QtCore.QSize(0, 25))
        self.fVendedorID.setSizeIncrement(QtCore.QSize(0, 25))
        self.fVendedorID.setProperty("clearButtonEnabled", True)
        self.fVendedorID.setObjectName("fVendedorID")
        self.gridLayout.addWidget(self.fVendedorID, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.fCustomerID = QtWidgets.QComboBox(Form)
        self.fCustomerID.setMinimumSize(QtCore.QSize(300, 25))
        self.fCustomerID.setSizeIncrement(QtCore.QSize(0, 25))
        self.fCustomerID.setObjectName("fCustomerID")
        self.gridLayout.addWidget(self.fCustomerID, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.fOrderDate = QtWidgets.QDateEdit(Form)
        self.fOrderDate.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fOrderDate.setCalendarPopup(True)
        self.fOrderDate.setObjectName("fOrderDate")
        self.gridLayout.addWidget(self.fOrderDate, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setMinimumSize(QtCore.QSize(0, 250))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fNote = QtWidgets.QTextEdit(Form)
        self.fNote.setToolTipDuration(-1)
        self.fNote.setStatusTip("")
        self.fNote.setWhatsThis("")
        self.fNote.setAccessibleName("")
        self.fNote.setLineWidth(-1)
        self.fNote.setObjectName("fNote")
        self.verticalLayout.addWidget(self.fNote)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.temp = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.temp.sizePolicy().hasHeightForWidth())
        self.temp.setSizePolicy(sizePolicy)
        self.temp.setObjectName("temp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.temp)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.temp)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(150, 25))
        self.label.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                                | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fAmount = QtWidgets.QLineEdit(self.temp)
        self.fAmount.setMinimumSize(QtCore.QSize(0, 25))
        self.fAmount.setMaximumSize(QtCore.QSize(150, 25))
        self.fAmount.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fAmount.setFont(font)
        self.fAmount.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fAmount.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.fAmount.setReadOnly(True)
        self.fAmount.setObjectName("fAmount")
        self.gridLayout_2.addWidget(self.fAmount, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.temp)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(150, 25))
        self.label_13.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_13.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.fDesconto = QtWidgets.QLineEdit(self.temp)
        self.fDesconto.setMinimumSize(QtCore.QSize(0, 25))
        self.fDesconto.setMaximumSize(QtCore.QSize(150, 25))
        self.fDesconto.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fDesconto.setFont(font)
        self.fDesconto.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fDesconto.setAlignment(QtCore.Qt.AlignRight
                                    | QtCore.Qt.AlignTrailing
                                    | QtCore.Qt.AlignVCenter)
        self.fDesconto.setObjectName("fDesconto")
        self.gridLayout_2.addWidget(self.fDesconto, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.temp)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(150, 25))
        self.label_14.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_14.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.fTax = QtWidgets.QLineEdit(self.temp)
        self.fTax.setMinimumSize(QtCore.QSize(0, 25))
        self.fTax.setMaximumSize(QtCore.QSize(150, 25))
        self.fTax.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fTax.setFont(font)
        self.fTax.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fTax.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                               | QtCore.Qt.AlignVCenter)
        self.fTax.setObjectName("fTax")
        self.gridLayout_2.addWidget(self.fTax, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.temp)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setMaximumSize(QtCore.QSize(150, 25))
        self.label_15.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.label_15.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.fPayable = QtWidgets.QLineEdit(self.temp)
        self.fPayable.setMinimumSize(QtCore.QSize(0, 25))
        self.fPayable.setMaximumSize(QtCore.QSize(150, 25))
        self.fPayable.setSizeIncrement(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fPayable.setFont(font)
        self.fPayable.setStyleSheet("border-width: 0.7px;border-style: solid")
        self.fPayable.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.fPayable.setReadOnly(True)
        self.fPayable.setObjectName("fPayable")
        self.gridLayout_2.addWidget(self.fPayable, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.temp)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        # self.fDesconto.editingFinished.connect(Form.ReCalc)
        # self.fTax.editingFinished.connect(Form.ReCalc)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Order"))
        self.butSave.setText(_translate("Form", "Save"))
        self.butPrint.setText(_translate("Form", "Print"))
        self.butPDF.setText(_translate("Form", "PDF"))
        self.label_2.setText(_translate("Form", "NO."))
        self.fSucursal.setText(_translate("Form", "Sucursal"))
        self.fRequiredDeliveryDate.setDisplayFormat(
            _translate("Form", "yyyy-MM-dd"))
        self.label_7.setText(_translate("Form", "税号NUIT:"))
        self.label_9.setText(_translate("Form", "地址Endereco:"))
        self.label_8.setText(_translate("Form", "城市City:"))
        self.label_12.setText(_translate("Form", "电话Tel:"))
        self.label_4.setText(_translate("Form", "交货日期Date:"))
        self.label_11.setText(_translate("Form", "联系人Contato:"))
        self.label_6.setText(_translate("Form", "客户名Cliente:"))
        self.label_10.setText(_translate("Form", "手机Celular:"))
        self.fCustomerID.setProperty(
            "placeholderText", _translate("Form", "Please select a cliente."))
        self.label_5.setText(_translate("Form", "销售Vendedor:"))
        self.label_3.setText(_translate("Form", "日期Date:"))
        self.fOrderDate.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.fNote.setPlaceholderText(_translate("Form", "Note："))
        self.label.setText(_translate("Form", "金额合计SubTota:"))
        self.label_13.setText(_translate("Form", "折扣Desconto:"))
        self.label_14.setText(_translate("Form", "税金IVA:"))
        self.label_15.setText(_translate("Form", "应付金额Valor a Pagar:"))


if __name__ == "__main__":
    import sys
    from lib.JPDatebase import JPMySqlSingleTableQuery as JPQ
    from lib.JPMvc.JPModel import JPFormModelMainSub

    from lib.JPFunction import JPRound, NV
    from PyQt5.QtWidgets import QMessageBox, QWidget as QWidget_
    from PyQt5 import Qt
    from PyQt5.QtCore import QModelIndex
    from functools import reduce
    from ZionPublc import JPPub

    pb = JPPub()
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    curPK = 'CP2019-0201000014'
    m_sql = """select fOrderID,fOrderDate,fVendedorID,fRequiredDeliveryDate,
            fCustomerID,fContato,fCelular,fTelefone,fAmount,fTax,
            fPayable,fDesconto,fNote from t_order
             where fOrderID='{}'""".format(curPK)
    s_sql = """select fID,fOrderID,fQuant as '数量Qtd',
            fProductName as '名称Descrição',fLength as '长Larg.',
            fWidth as '宽Comp.',fPrice as '单价P. Unitario',
            fAmount as '金额Total' from t_order_detail 
            where fOrderID='{}'""".format(curPK)

    def checkBeforeNewRow(data_all, r, c):
        data = data_all[len(data_all) - 1]
        if data[7] is None or data[7] == 0:
            return False
        lt = [data[2], data[4], data[5], data[6], data[7]]
        lt = [float(str(i)) if i else 0 for i in lt]
        return int(lt[4] * 100) == int(
            reduce(lambda x, y: x * y, lt[0:4]) * 100)

    MF = JPFormModelMainSub(Form, ui.tableView)
    MF.mainModel.setFieldsRowSource([
        'fCustomerID',
        pb.getCustomerList(), 'fVendedorID',
        pb.user.getAllUserEnumList()
    ])

    MF.mainModel.setTabelInfo(m_sql)
    MF.subModel.setColumnsHidden(0, 1)
    MF.subModel.setColumnWidths(0, 0, 60, 300, 100, 100, 100, 100)
    MF.subModel.setColumnsReadOnly(7)
    MF.subModel.setTabelInfo(s_sql)
    MF.subModel.setAutoAddRow(checkBeforeNewRow, False)
    Formula = "JPRound(JPRound({2}) * JPRound({4}) * JPRound({5}) * JPRound({6}))"
    MF.subModel.setFormula(7, Formula)

    def butSave():
        try:
            MF.subModel.GetSQLS()
        except Exception as e:
            msgBox = QMessageBox(QMessageBox.Critical, u'提示', str(e))
            msgBox.exec_()

    def cusChange(r):
        obj = ui.fCustomerID
        row = obj.RowSource[r]
        ui.fNUIT.setText(row[2])
        ui.fCity.setText(row[3])

    ui.fCustomerID.currentIndexChanged.connect(cusChange)

    def Cacu(*args):
        M = MF.mainModel
        v_sum = MF.subModel.getColumnSum(7)
        fDesconto = M.getObjectValue("fDesconto")
        fTax = (v_sum - fDesconto) * 0.17
        fPayable = v_sum - fDesconto + fTax
        M.setObjectValue('fAmount', v_sum)
        M.setObjectValue("fTax", fTax)
        M.setObjectValue("fPayable", fPayable)

    ui.butSave.clicked.connect(butSave)
    MF.dataChanged[QModelIndex].connect(Cacu)
    MF.dataChanged[QWidget_].connect(Cacu)
    MF.show(JPFormModelMainSub.Edit)

    sys.exit(app.exec_())
    app.exec_()
