# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Zion\zion\Ui\FormProductList.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1094, 677)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_Button = QtWidgets.QWidget(self.layoutWidget)
        self.widget_Button.setObjectName("widget_Button")
        self.Layout_Button = QtWidgets.QHBoxLayout(self.widget_Button)
        self.Layout_Button.setContentsMargins(0, 0, 0, 0)
        self.Layout_Button.setSpacing(0)
        self.Layout_Button.setObjectName("Layout_Button")
        self.horizontalLayout_2.addWidget(self.widget_Button)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_2.addWidget(self.tableView)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 22))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.CmdExportToExcel_Low = QtWidgets.QPushButton(self.frame)
        self.CmdExportToExcel_Low.setObjectName("CmdExportToExcel_Low")
        self.horizontalLayout_3.addWidget(self.CmdExportToExcel_Low)
        self.CmdPrint_Low = QtWidgets.QPushButton(self.frame)
        self.CmdPrint_Low.setObjectName("CmdPrint_Low")
        self.horizontalLayout_3.addWidget(self.CmdPrint_Low)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView_low = QtWidgets.QTableView(self.frame)
        self.tableView_low.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_low.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_low.setObjectName("tableView_low")
        self.tableView_low.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout.addWidget(self.tableView_low)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.dateBegin = QtWidgets.QDateEdit(self.frame_3)
        self.dateBegin.setMaximumSize(QtCore.QSize(16777215, 22))
        self.dateBegin.setCalendarPopup(True)
        self.dateBegin.setObjectName("dateBegin")
        self.horizontalLayout.addWidget(self.dateBegin)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setSizeIncrement(QtCore.QSize(10, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.dateEditEnd = QtWidgets.QDateEdit(self.frame_3)
        self.dateEditEnd.setCalendarPopup(True)
        self.dateEditEnd.setObjectName("dateEditEnd")
        self.horizontalLayout.addWidget(self.dateEditEnd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.CmdExportToExcel_Detail = QtWidgets.QPushButton(self.frame_3)
        self.CmdExportToExcel_Detail.setObjectName("CmdExportToExcel_Detail")
        self.horizontalLayout.addWidget(self.CmdExportToExcel_Detail)
        self.CmdPrint_Detail = QtWidgets.QPushButton(self.frame_3)
        self.CmdPrint_Detail.setObjectName("CmdPrint_Detail")
        self.horizontalLayout.addWidget(self.CmdPrint_Detail)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.tableView_rec = QtWidgets.QTableView(self.frame_2)
        self.tableView_rec.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_rec.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_rec.setObjectName("tableView_rec")
        self.tableView_rec.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_3.addWidget(self.tableView_rec)
        self.verticalLayout_4.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        #QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "   Find："))
        self.label_2.setText(_translate("Form", " 低库存预警Early Warning of Low Inventory："))
        self.CmdExportToExcel_Low.setText(_translate("Form", "ExportToExcel"))
        self.CmdPrint_Low.setText(_translate("Form", "Print"))
        self.label_4.setText(_translate("Form", " 出入库明细Detail："))
        self.label_3.setText(_translate("Form", "起止日期Date："))
        self.dateBegin.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_5.setText(_translate("Form", "--"))
        self.dateEditEnd.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.CmdExportToExcel_Detail.setText(_translate("Form", "ExportToExcel"))
        self.CmdPrint_Detail.setText(_translate("Form", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
