# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Zion\zion\Ui\FormCustomer_Arrears.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 353)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_Button = QtWidgets.QWidget(Form)
        self.widget_Button.setObjectName("widget_Button")
        self.Layout_Button = QtWidgets.QHBoxLayout(self.widget_Button)
        self.Layout_Button.setContentsMargins(0, 0, 0, 0)
        self.Layout_Button.setSpacing(0)
        self.Layout_Button.setObjectName("Layout_Button")
        self.horizontalLayout_2.addWidget(self.widget_Button)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tableView = QtWidgets.QTableView(self.splitter_2)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setDefaultSectionSize(25)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CmdExportExcel_BillDetail = QtWidgets.QPushButton(self.layoutWidget)
        self.CmdExportExcel_BillDetail.setObjectName("CmdExportExcel_BillDetail")
        self.horizontalLayout.addWidget(self.CmdExportExcel_BillDetail)
        self.CmdPrint_BillDetail = QtWidgets.QPushButton(self.layoutWidget)
        self.CmdPrint_BillDetail.setObjectName("CmdPrint_BillDetail")
        self.horizontalLayout.addWidget(self.CmdPrint_BillDetail)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_order = QtWidgets.QTableView(self.layoutWidget)
        self.tableView_order.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_order.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_order.setObjectName("tableView_order")
        self.tableView_order.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout.addWidget(self.tableView_order)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.CmdExportExcel_RecDetail = QtWidgets.QPushButton(self.layoutWidget1)
        self.CmdExportExcel_RecDetail.setObjectName("CmdExportExcel_RecDetail")
        self.horizontalLayout_3.addWidget(self.CmdExportExcel_RecDetail)
        self.CmdPrint_RecDetail = QtWidgets.QPushButton(self.layoutWidget1)
        self.CmdPrint_RecDetail.setObjectName("CmdPrint_RecDetail")
        self.horizontalLayout_3.addWidget(self.CmdPrint_RecDetail)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tableView_rec = QtWidgets.QTableView(self.layoutWidget1)
        self.tableView_rec.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_rec.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_rec.setObjectName("tableView_rec")
        self.tableView_rec.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_2.addWidget(self.tableView_rec)
        self.verticalLayout_3.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Find："))
        self.label_2.setText(_translate("Form", "单据明细"))
        self.CmdExportExcel_BillDetail.setText(_translate("Form", "ExportToExcel"))
        self.CmdPrint_BillDetail.setText(_translate("Form", "Print"))
        self.label_3.setText(_translate("Form", "收款明细"))
        self.CmdExportExcel_RecDetail.setText(_translate("Form", "ExportToExcel"))
        self.CmdPrint_RecDetail.setText(_translate("Form", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
