# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Zion\Ui\FormReceivables.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(951, 359)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.butRecibido = QtWidgets.QPushButton(self.frame_2)
        self.butRecibido.setIconSize(QtCore.QSize(16, 16))
        self.butRecibido.setObjectName("butRecibido")
        self.horizontalLayout_2.addWidget(self.butRecibido)
        self.butRefresh = QtWidgets.QPushButton(self.frame_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ico/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butRefresh.setIcon(icon)
        self.butRefresh.setIconSize(QtCore.QSize(16, 16))
        self.butRefresh.setObjectName("butRefresh")
        self.horizontalLayout_2.addWidget(self.butRefresh)
        self.butExportToExcel = QtWidgets.QPushButton(self.frame_2)
        self.butExportToExcel.setIcon(icon)
        self.butExportToExcel.setIconSize(QtCore.QSize(16, 16))
        self.butExportToExcel.setObjectName("butExportToExcel")
        self.horizontalLayout_2.addWidget(self.butExportToExcel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.SelectDate = QtWidgets.QDateEdit(self.frame_2)
        self.SelectDate.setCalendarPopup(True)
        self.SelectDate.setObjectName("SelectDate")
        self.horizontalLayout.addWidget(self.SelectDate)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabCurrentDayRec = QtWidgets.QTableView(self.frame_2)
        self.tabCurrentDayRec.setMinimumSize(QtCore.QSize(0, 100))
        self.tabCurrentDayRec.setMaximumSize(QtCore.QSize(16777214, 500))
        self.tabCurrentDayRec.setObjectName("tabCurrentDayRec")
        self.tabCurrentDayRec.verticalHeader().setDefaultSectionSize(25)
        self.tabCurrentDayRec.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout.addWidget(self.tabCurrentDayRec)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 15))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.tabCustomerRecorder = QtWidgets.QTableView(self.layoutWidget)
        self.tabCustomerRecorder.setMinimumSize(QtCore.QSize(100, 0))
        self.tabCustomerRecorder.setObjectName("tabCustomerRecorder")
        self.tabCustomerRecorder.verticalHeader().setDefaultSectionSize(25)
        self.tabCustomerRecorder.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_3.addWidget(self.tabCustomerRecorder)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.tabCustomerArrearsList = QtWidgets.QTableView(self.layoutWidget1)
        self.tabCustomerArrearsList.setMinimumSize(QtCore.QSize(100, 0))
        self.tabCustomerArrearsList.setObjectName("tabCustomerArrearsList")
        self.tabCustomerArrearsList.verticalHeader().setDefaultSectionSize(25)
        self.tabCustomerArrearsList.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_4.addWidget(self.tabCustomerArrearsList)
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.butRecibido.setText(_translate("Form", "Recibido"))
        self.butRefresh.setText(_translate("Form", "Refresh"))
        self.butExportToExcel.setText(_translate("Form", "ExportToExcel"))
        self.label_5.setText(_translate("Form", "Daily Rreport:"))
        self.SelectDate.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.label.setText(_translate("Form", "Receivables"))
        self.label_4.setText(_translate("Form", "Customer Recorder:"))
        self.label_2.setText(_translate("Form", "Customer Arrears:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

